"""add_analytics_tables

Revision ID: 879095501154
Revises: b0fedb190c6d
Create Date: 2026-05-20 17:27:05.507369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879095501154'
down_revision: Union[str, None] = 'b0fedb190c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots')),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_snapshots_portfolio_date')
    )
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('stock_scores',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('momentum_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('volatility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('volume_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_stock_scores_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_scores'))
    )
    op.create_index(op.f('ix_stock_scores_instrument_id'), 'stock_scores', ['instrument_id'], unique=True)
    op.create_table('technical_indicators',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('indicator_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_technical_indicators_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_indicators'))
    )
    op.create_index(op.f('ix_technical_indicators_instrument_id'), 'technical_indicators', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_indicators_instrument_id'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_stock_scores_instrument_id'), table_name='stock_scores')
    op.drop_table('stock_scores')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
