"""add_company_info_to_instruments

Revision ID: c8ae0ca57237
Revises: 2c0db484b049
Create Date: 2026-06-15 12:42:08.243269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ae0ca57237'
down_revision: Union[str, None] = '2c0db484b049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('instruments', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('instruments', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('instruments', sa.Column('market_cap', sa.BigInteger(), nullable=True))
    op.add_column('instruments', sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('instruments', sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('instruments', sa.Column('dividend_yield', sa.Numeric(precision=8, scale=6), nullable=True))
    op.add_column('instruments', sa.Column('fifty_two_week_high', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('instruments', sa.Column('fifty_two_week_low', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('instruments', sa.Column('avg_volume', sa.BigInteger(), nullable=True))
    op.add_column('instruments', sa.Column('info_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'info_updated_at')
    op.drop_column('instruments', 'avg_volume')
    op.drop_column('instruments', 'fifty_two_week_low')
    op.drop_column('instruments', 'fifty_two_week_high')
    op.drop_column('instruments', 'dividend_yield')
    op.drop_column('instruments', 'eps')
    op.drop_column('instruments', 'pe_ratio')
    op.drop_column('instruments', 'market_cap')
    op.drop_column('instruments', 'website')
    op.drop_column('instruments', 'country')
    op.drop_column('instruments', 'description')
    # ### end Alembic commands ###
